services:
  db:
    image: postgres:16
    container_name: restaurant_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: restaurant_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d restaurant_db"]
      interval: 2s
      timeout: 2s
      retries: 10
    env_file:
      - .env

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restaurant_api
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:postgres@db:5432/restaurant_db
    networks:
      - app-network
    volumes:
      - ./src/static:/app/src/static
    command: >
      sh -c "alembic upgrade head && 
      uvicorn src.main:app --host 0.0.0.0 --port 8000"
    env_file:
      - .env



volumes:
  pgdata:

networks:
  app-network:
    driver: bridge